#!/usr/bin/env ruby
#
require 'fileutils'
require 'open-uri'

git_bundles = %w(
  git://github.com/ervandew/supertab.git
  git://github.com/godlygeek/tabular.git
  git://github.com/lukerandall/haskellmode-vim.git
  git://github.com/msanders/snipmate.vim.git
  git://github.com/tomtom/tcomment_vim.git
  git://github.com/tpope/vim-commentary.git
  git://github.com/tpope/vim-endwise.git
  git://github.com/tpope/vim-fugitive.git
  git://github.com/tpope/vim-git.git
  git://github.com/tpope/vim-markdown.git
  git://github.com/tpope/vim-pathogen.git
  git://github.com/tpope/vim-repeat.git
  git://github.com/tpope/vim-speeddating.git
  git://github.com/tpope/vim-surround.git
  git://github.com/tpope/vim-unimpaired.git
  git://github.com/tsaleh/vim-tmux.git
  git://github.com/vim-scripts/LaTeX-Suite-aka-Vim-LaTeX.git
  git://github.com/vim-scripts/jQuery.git
  git://github.com/vim-scripts/jellybeans.vim.git
  git://github.com/vim-scripts/localvimrc.git
  git://github.com/vim-scripts/matchit.zip.git
  git://github.com/vim-scripts/netrw.vim.git
  git://github.com/vim-scripts/taglist.vim.git
)

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.mkdir_p bundles_dir
FileUtils.cd      bundles_dir

git_bundles.each do |url|
  dir = url.split('/').last.
        sub(/\.git$/, '').
        sub(/vim[-._]+/,'').
        sub(/[-._]+vim/,'').
        sub(/\.zip/,'')
  if FileTest.directory? dir
    $stdout.puts "updating dir #{dir}"
    $stdout.flush
    %x((cd #{dir}; git pull))
  else
    $stdout.puts "unpacking #{url} into #{dir}"
    $stdout.flush
    %x(git clone #{url} #{dir})
  end
end
