[ -e ~/.profile ] && source ~/.profile

ZDOTDIR=~/.zsh

setopt extended_glob
for f in $ZDOTDIR/[0-9][0-9][^.]#; do
    . $f
done

#keychain -q id_rsa
#source ~/.keychain/$HOST-sh

# use .localrc for settings specific to one system
[[ -f ~/.localrc ]] && .  ~/.localrc
